name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Generate Documentation
        run: go doc -all > docs/package.md

      - name: Deploy Documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          mkdir -p ./.go-docs
          mv docs/* ./.go-docs/
          git add .
          git commit -m "Auto-generate documentation"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
